name: Build and deploy ASP.Net Core app to Azure Web App - user-service-api-axel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore userservice/userservice.csproj

      - name: Build project
        run: dotnet build userservice/userservice.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish userservice/userservice.csproj --configuration Release --output ${{ github.workspace }}/publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'user-service-api-axel'
          package: ${{ github.workspace }}/publish
          
