name: Build and deploy ASP.Net Core app to Azure Web App - user-service-api-axel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build userservice/userservice.csproj --configuration Release

      - name: Publish project
        run: dotnet publish userservice/userservice.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'user-service-api-axel'
          slot-name: 'Production'
          package: './publish'


          
